(define (problem drone_problem_d1_l7_p7_c7_g7_ct2)
(:domain dominio-drones-2)
(:objects
	dron1 - dron
	deposito loc1 loc2 loc3 loc4 loc5 loc6 loc7 - localizacion
	caja1 caja2 caja3 caja4 caja5 caja6 caja7 - caja
	comida medicina - contenido
	pers1 pers2 pers3 pers4 pers5 pers6 pers7 - persona
	k1 - contenedor
n0 n1 n2 n3 n4 - num
)
(:init
	(dron-en dron1 deposito)
	(dron-libre dron1)
	(dron-sin-caja dron1)

	(en-deposito deposito) 
	(contenedor-libre k1)

	(caja-en caja1 deposito) (caja-libre caja1)(contiene caja1 comida)
	(caja-en caja2 deposito) (caja-libre caja2)(contiene caja2 comida)
	(caja-en caja3 deposito) (caja-libre caja3)(contiene caja3 comida)
	(caja-en caja4 deposito) (caja-libre caja4)(contiene caja4 comida)

	(caja-en caja5 deposito)(caja-libre caja5)(contiene caja5 medicina)
	(caja-en caja6 deposito)(caja-libre caja6)(contiene caja6 medicina)
	(caja-en caja7 deposito)(caja-libre caja7)(contiene caja7 medicina)

	(persona-en pers1 loc1)(necesita pers1 comida)
	(persona-en pers2 loc2)(necesita pers2 medicina)
	(persona-en pers3 loc3)(necesita pers3 comida)
	(persona-en pers4 loc4)(necesita pers4 comida)
(necesita pers4 medicina)
	(persona-en pers5 loc5)(necesita pers5 medicina)
	(persona-en pers6 loc6)(necesita pers6 comida)
	(persona-en pers7 loc7)

	(= (fly-cost deposito loc1) 28)
	(= (fly-cost deposito loc2) 47)
	(= (fly-cost deposito loc3) 21)
	(= (fly-cost deposito loc4) 16)
	(= (fly-cost deposito loc5) 38)
	(= (fly-cost deposito loc6) 36)
	(= (fly-cost deposito loc7) 43)
	(= (fly-cost loc1 deposito) 28)
	(= (fly-cost loc1 loc2) 26)
	(= (fly-cost loc1 loc3) 14)
	(= (fly-cost loc1 loc4) 21)
	(= (fly-cost loc1 loc5) 29)
	(= (fly-cost loc1 loc6) 10)
	(= (fly-cost loc1 loc7) 27)
	(= (fly-cost loc2 deposito) 47)
	(= (fly-cost loc2 loc1) 26)
	(= (fly-cost loc2 loc3) 27)
	(= (fly-cost loc2 loc4) 34)
	(= (fly-cost loc2 loc5) 19)
	(= (fly-cost loc2 loc6) 29)
	(= (fly-cost loc2 loc7) 8)
	(= (fly-cost loc3 deposito) 21)
	(= (fly-cost loc3 loc1) 14)
	(= (fly-cost loc3 loc2) 27)
	(= (fly-cost loc3 loc4) 9)
	(= (fly-cost loc3 loc5) 20)
	(= (fly-cost loc3 loc6) 24)
	(= (fly-cost loc3 loc7) 23)
	(= (fly-cost loc4 deposito) 16)
	(= (fly-cost loc4 loc1) 21)
	(= (fly-cost loc4 loc2) 34)
	(= (fly-cost loc4 loc3) 9)
	(= (fly-cost loc4 loc5) 22)
	(= (fly-cost loc4 loc6) 31)
	(= (fly-cost loc4 loc7) 29)
	(= (fly-cost loc5 deposito) 38)
	(= (fly-cost loc5 loc1) 29)
	(= (fly-cost loc5 loc2) 19)
	(= (fly-cost loc5 loc3) 20)
	(= (fly-cost loc5 loc4) 22)
	(= (fly-cost loc5 loc6) 36)
	(= (fly-cost loc5 loc7) 12)
	(= (fly-cost loc6 deposito) 36)
	(= (fly-cost loc6 loc1) 10)
	(= (fly-cost loc6 loc2) 29)
	(= (fly-cost loc6 loc3) 24)
	(= (fly-cost loc6 loc4) 31)
	(= (fly-cost loc6 loc5) 36)
	(= (fly-cost loc6 loc7) 31)
	(= (fly-cost loc7 deposito) 43)
	(= (fly-cost loc7 loc1) 27)
	(= (fly-cost loc7 loc2) 8)
	(= (fly-cost loc7 loc3) 23)
	(= (fly-cost loc7 loc4) 29)
	(= (fly-cost loc7 loc5) 12)
	(= (fly-cost loc7 loc6) 31)

	(cajas-en-contenedor k1 n0)

	(cero n0) 
	(siguiente n0 n1) 
	(siguiente n1 n2) 
	(siguiente n2 n3) 
	(siguiente n3 n4)	(= (total-cost) 0)
)
(:goal (and
	(dron-en dron1 deposito)
	(tiene pers1 comida)
	(tiene pers2 medicina)
	(tiene pers3 comida)
	(tiene pers4 comida)
	(tiene pers4 medicina)
	(tiene pers5 medicina)
	(tiene pers6 comida)
	))
(:metric minimize (total-cost)))
