(define (problem drone_problem_d1_l8_p8_c8_g8_ct2)
(:domain dominio-drones-2)
(:objects
	dron1 - dron
	deposito loc1 loc2 loc3 loc4 loc5 loc6 loc7 loc8 - localizacion
	caja1 caja2 caja3 caja4 caja5 caja6 caja7 caja8 - caja
	comida medicina - contenido
	pers1 pers2 pers3 pers4 pers5 pers6 pers7 pers8 - persona
	k1 - contenedor
n0 n1 n2 n3 n4 - num
)
(:init
	(dron-en dron1 deposito)
	(dron-libre dron1)
	(dron-sin-caja dron1)

	(en-deposito deposito) 
	(contenedor-libre k1)

	(caja-en caja1 deposito) (caja-libre caja1)(contiene caja1 comida)
	(caja-en caja2 deposito) (caja-libre caja2)(contiene caja2 comida)
	(caja-en caja3 deposito) (caja-libre caja3)(contiene caja3 comida)
	(caja-en caja4 deposito) (caja-libre caja4)(contiene caja4 comida)
	(caja-en caja5 deposito) (caja-libre caja5)(contiene caja5 comida)
	(caja-en caja6 deposito) (caja-libre caja6)(contiene caja6 comida)

	(caja-en caja7 deposito)(caja-libre caja7)(contiene caja7 medicina)
	(caja-en caja8 deposito)(caja-libre caja8)(contiene caja8 medicina)

	(persona-en pers1 loc1)
	(persona-en pers2 loc2)(necesita pers2 comida)
	(persona-en pers3 loc3)(necesita pers3 comida)
	(persona-en pers4 loc4)(necesita pers4 comida)
	(persona-en pers5 loc5)(necesita pers5 comida)
(necesita pers5 medicina)
	(persona-en pers6 loc6)
	(persona-en pers7 loc7)(necesita pers7 comida)
	(persona-en pers8 loc8)(necesita pers8 comida)
(necesita pers8 medicina)

	(= (fly-cost deposito loc1) 17)
	(= (fly-cost deposito loc2) 36)
	(= (fly-cost deposito loc3) 15)
	(= (fly-cost deposito loc4) 26)
	(= (fly-cost deposito loc5) 26)
	(= (fly-cost deposito loc6) 6)
	(= (fly-cost deposito loc7) 19)
	(= (fly-cost deposito loc8) 29)
	(= (fly-cost loc1 deposito) 17)
	(= (fly-cost loc1 loc2) 30)
	(= (fly-cost loc1 loc3) 3)
	(= (fly-cost loc1 loc4) 17)
	(= (fly-cost loc1 loc5) 19)
	(= (fly-cost loc1 loc6) 12)
	(= (fly-cost loc1 loc7) 7)
	(= (fly-cost loc1 loc8) 20)
	(= (fly-cost loc2 deposito) 36)
	(= (fly-cost loc2 loc1) 30)
	(= (fly-cost loc2 loc3) 31)
	(= (fly-cost loc2 loc4) 14)
	(= (fly-cost loc2 loc5) 12)
	(= (fly-cost loc2 loc6) 35)
	(= (fly-cost loc2 loc7) 24)
	(= (fly-cost loc2 loc8) 12)
	(= (fly-cost loc3 deposito) 15)
	(= (fly-cost loc3 loc1) 3)
	(= (fly-cost loc3 loc2) 31)
	(= (fly-cost loc3 loc4) 18)
	(= (fly-cost loc3 loc5) 19)
	(= (fly-cost loc3 loc6) 10)
	(= (fly-cost loc3 loc7) 8)
	(= (fly-cost loc3 loc8) 21)
	(= (fly-cost loc4 deposito) 26)
	(= (fly-cost loc4 loc1) 17)
	(= (fly-cost loc4 loc2) 14)
	(= (fly-cost loc4 loc3) 18)
	(= (fly-cost loc4 loc5) 5)
	(= (fly-cost loc4 loc6) 24)
	(= (fly-cost loc4 loc7) 11)
	(= (fly-cost loc4 loc8) 4)
	(= (fly-cost loc5 deposito) 26)
	(= (fly-cost loc5 loc1) 19)
	(= (fly-cost loc5 loc2) 12)
	(= (fly-cost loc5 loc3) 19)
	(= (fly-cost loc5 loc4) 5)
	(= (fly-cost loc5 loc6) 24)
	(= (fly-cost loc5 loc7) 13)
	(= (fly-cost loc5 loc8) 5)
	(= (fly-cost loc6 deposito) 6)
	(= (fly-cost loc6 loc1) 12)
	(= (fly-cost loc6 loc2) 35)
	(= (fly-cost loc6 loc3) 10)
	(= (fly-cost loc6 loc4) 24)
	(= (fly-cost loc6 loc5) 24)
	(= (fly-cost loc6 loc7) 15)
	(= (fly-cost loc6 loc8) 26)
	(= (fly-cost loc7 deposito) 19)
	(= (fly-cost loc7 loc1) 7)
	(= (fly-cost loc7 loc2) 24)
	(= (fly-cost loc7 loc3) 8)
	(= (fly-cost loc7 loc4) 11)
	(= (fly-cost loc7 loc5) 13)
	(= (fly-cost loc7 loc6) 15)
	(= (fly-cost loc7 loc8) 14)
	(= (fly-cost loc8 deposito) 29)
	(= (fly-cost loc8 loc1) 20)
	(= (fly-cost loc8 loc2) 12)
	(= (fly-cost loc8 loc3) 21)
	(= (fly-cost loc8 loc4) 4)
	(= (fly-cost loc8 loc5) 5)
	(= (fly-cost loc8 loc6) 26)
	(= (fly-cost loc8 loc7) 14)

	(cajas-en-contenedor k1 n0)

	(cero n0) 
	(siguiente n0 n1) 
	(siguiente n1 n2) 
	(siguiente n2 n3) 
	(siguiente n3 n4)	(= (total-cost) 0)
)
(:goal (and
	(dron-en dron1 deposito)
	(tiene pers2 comida)
	(tiene pers3 comida)
	(tiene pers4 comida)
	(tiene pers5 comida)
	(tiene pers5 medicina)
	(tiene pers7 comida)
	(tiene pers8 comida)
	(tiene pers8 medicina)
	))
(:metric minimize (total-cost)))
