(define (problem drone_problem_d1_r1_l18_p18_c18_g18_ct2)
(:domain dominio-drones)
(:objects
	dron1 - dron
	deposito loc1 loc2 loc3 loc4 loc5 loc6 loc7 loc8 loc9 loc10 loc11 loc12 loc13 loc14 loc15 loc16 loc17 loc18 - localizacion
	caja1 caja2 caja3 caja4 caja5 caja6 caja7 caja8 caja9 caja10 caja11 caja12 caja13 caja14 caja15 caja16 caja17 caja18 - caja
	comida medicina - contenido
	pers1 pers2 pers3 pers4 pers5 pers6 pers7 pers8 pers9 pers10 pers11 pers12 pers13 pers14 pers15 pers16 pers17 pers18 - persona
	brazo1 - brazo
)
(:init
	(dron-en dron1 deposito)
	(brazo-libre dron1 brazo1)

	(caja-en caja1 deposito)(contiene caja1 comida)
	(caja-en caja2 deposito)(contiene caja2 comida)
	(caja-en caja3 deposito)(contiene caja3 comida)
	(caja-en caja4 deposito)(contiene caja4 comida)
	(caja-en caja5 deposito)(contiene caja5 comida)
	(caja-en caja6 deposito)(contiene caja6 comida)
	(caja-en caja7 deposito)(contiene caja7 comida)
	(caja-en caja8 deposito)(contiene caja8 comida)
	(caja-en caja9 deposito)(contiene caja9 comida)
	(caja-en caja10 deposito)(contiene caja10 comida)
	(caja-en caja11 deposito)(contiene caja11 comida)
	(caja-en caja12 deposito)(contiene caja12 comida)
	(caja-en caja13 deposito)(contiene caja13 comida)
	(caja-en caja14 deposito)(contiene caja14 comida)
	(caja-en caja15 deposito)(contiene caja15 medicina)
	(caja-en caja16 deposito)(contiene caja16 medicina)
	(caja-en caja17 deposito)(contiene caja17 medicina)
	(caja-en caja18 deposito)(contiene caja18 medicina)
	(persona-en pers1 loc1)(necesita pers1 comida)
	(persona-en pers2 loc2)(necesita pers2 comida)
	(persona-en pers3 loc3)(necesita pers3 comida)
	(persona-en pers4 loc4)	(persona-en pers5 loc5)(necesita pers5 comida)
	(persona-en pers6 loc6)	(persona-en pers7 loc7)(necesita pers7 comida)
	(persona-en pers8 loc8)(necesita pers8 comida)
	(persona-en pers9 loc9)(necesita pers9 comida)
	(persona-en pers10 loc10)(necesita pers10 comida)
	(persona-en pers11 loc11)(necesita pers11 comida)
(necesita pers11 medicina)
	(persona-en pers12 loc12)	(persona-en pers13 loc13)(necesita pers13 comida)
	(persona-en pers14 loc14)(necesita pers14 comida)
(necesita pers14 medicina)
	(persona-en pers15 loc15)(necesita pers15 comida)
	(persona-en pers16 loc16)	(persona-en pers17 loc17)(necesita pers17 comida)
(necesita pers17 medicina)
	(persona-en pers18 loc18)(necesita pers18 comida)
(necesita pers18 medicina)
)
(:goal (and
	(dron-en dron1 deposito)
	(tiene pers1 comida)
	(tiene pers2 comida)
	(tiene pers3 comida)
	(tiene pers5 comida)
	(tiene pers7 comida)
	(tiene pers8 comida)
	(tiene pers9 comida)
	(tiene pers10 comida)
	(tiene pers11 comida)
	(tiene pers11 medicina)
	(tiene pers13 comida)
	(tiene pers14 comida)
	(tiene pers14 medicina)
	(tiene pers15 comida)
	(tiene pers17 comida)
	(tiene pers17 medicina)
	(tiene pers18 comida)
	(tiene pers18 medicina)
	))
)
