(define (problem drone_problem_d1_r1_l23_p23_c23_g23_ct2)
(:domain dominio-drones)
(:objects
	dron1 - dron
	deposito loc1 loc2 loc3 loc4 loc5 loc6 loc7 loc8 loc9 loc10 loc11 loc12 loc13 loc14 loc15 loc16 loc17 loc18 loc19 loc20 loc21 loc22 loc23 - localizacion
	caja1 caja2 caja3 caja4 caja5 caja6 caja7 caja8 caja9 caja10 caja11 caja12 caja13 caja14 caja15 caja16 caja17 caja18 caja19 caja20 caja21 caja22 caja23 - caja
	comida medicina - contenido
	pers1 pers2 pers3 pers4 pers5 pers6 pers7 pers8 pers9 pers10 pers11 pers12 pers13 pers14 pers15 pers16 pers17 pers18 pers19 pers20 pers21 pers22 pers23 - persona
	brazo1 - brazo
)
(:init
	(dron-en dron1 deposito)
	(brazo-libre dron1 brazo1)

	(caja-en caja1 deposito)(contiene caja1 comida)
	(caja-en caja2 deposito)(contiene caja2 comida)
	(caja-en caja3 deposito)(contiene caja3 comida)
	(caja-en caja4 deposito)(contiene caja4 comida)
	(caja-en caja5 deposito)(contiene caja5 comida)
	(caja-en caja6 deposito)(contiene caja6 comida)
	(caja-en caja7 deposito)(contiene caja7 comida)
	(caja-en caja8 deposito)(contiene caja8 comida)
	(caja-en caja9 deposito)(contiene caja9 comida)
	(caja-en caja10 deposito)(contiene caja10 comida)
	(caja-en caja11 deposito)(contiene caja11 comida)
	(caja-en caja12 deposito)(contiene caja12 comida)
	(caja-en caja13 deposito)(contiene caja13 comida)
	(caja-en caja14 deposito)(contiene caja14 medicina)
	(caja-en caja15 deposito)(contiene caja15 medicina)
	(caja-en caja16 deposito)(contiene caja16 medicina)
	(caja-en caja17 deposito)(contiene caja17 medicina)
	(caja-en caja18 deposito)(contiene caja18 medicina)
	(caja-en caja19 deposito)(contiene caja19 medicina)
	(caja-en caja20 deposito)(contiene caja20 medicina)
	(caja-en caja21 deposito)(contiene caja21 medicina)
	(caja-en caja22 deposito)(contiene caja22 medicina)
	(caja-en caja23 deposito)(contiene caja23 medicina)
	(persona-en pers1 loc1)(necesita pers1 medicina)
	(persona-en pers2 loc2)(necesita pers2 comida)
	(persona-en pers3 loc3)	(persona-en pers4 loc4)(necesita pers4 comida)
	(persona-en pers5 loc5)(necesita pers5 comida)
	(persona-en pers6 loc6)(necesita pers6 medicina)
	(persona-en pers7 loc7)	(persona-en pers8 loc8)	(persona-en pers9 loc9)(necesita pers9 comida)
(necesita pers9 medicina)
	(persona-en pers10 loc10)	(persona-en pers11 loc11)(necesita pers11 comida)
(necesita pers11 medicina)
	(persona-en pers12 loc12)(necesita pers12 comida)
	(persona-en pers13 loc13)(necesita pers13 medicina)
	(persona-en pers14 loc14)(necesita pers14 comida)
	(persona-en pers15 loc15)(necesita pers15 comida)
(necesita pers15 medicina)
	(persona-en pers16 loc16)(necesita pers16 comida)
(necesita pers16 medicina)
	(persona-en pers17 loc17)	(persona-en pers18 loc18)(necesita pers18 comida)
(necesita pers18 medicina)
	(persona-en pers19 loc19)(necesita pers19 comida)
(necesita pers19 medicina)
	(persona-en pers20 loc20)	(persona-en pers21 loc21)(necesita pers21 comida)
(necesita pers21 medicina)
	(persona-en pers22 loc22)	(persona-en pers23 loc23)(necesita pers23 comida)
)
(:goal (and
	(dron-en dron1 deposito)
	(tiene pers1 medicina)
	(tiene pers2 comida)
	(tiene pers4 comida)
	(tiene pers5 comida)
	(tiene pers6 medicina)
	(tiene pers9 comida)
	(tiene pers9 medicina)
	(tiene pers11 comida)
	(tiene pers11 medicina)
	(tiene pers12 comida)
	(tiene pers13 medicina)
	(tiene pers14 comida)
	(tiene pers15 comida)
	(tiene pers15 medicina)
	(tiene pers16 comida)
	(tiene pers16 medicina)
	(tiene pers18 comida)
	(tiene pers18 medicina)
	(tiene pers19 comida)
	(tiene pers19 medicina)
	(tiene pers21 comida)
	(tiene pers21 medicina)
	(tiene pers23 comida)
	))
)
